### ISSUE TITLE
No current event loop in thread "ScriptRunner.scriptThread"

### ISSUE THREAD

**Issue by zhuofan-16** [NVIDIA/NeMo-Guardrails#119]
Project was working well. However , when I attempt to import nemoguardrails, this will occur

`2023-09-13 15:03:15.428 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\-py3.8\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\\ai-llm\src\app.py", line 3, in <module>
    from  orchestration_layer import chatbot as bot
  File "C:\Users\\ai-llm\src\orchestration_layer\chatbot.py", line 5, in <module>
    from nemoguardrails import LLMRails, RailsConfig
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\-py3.8\lib\site-packages\nemoguardrails\__init__.py", line 20, in <module>
    patch_asyncio.apply()
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\-py3.8\lib\site-packages\nemoguardrails\patch_asyncio.py", line 33, in apply
    nest_asyncio.apply()
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\-py3.8\lib\site-packages\nest_asyncio.py", line 18, in apply
    loop = loop or asyncio.get_event_loop()
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'.
`

**Comment by zhuofan-16** [comment]
I switch to 0.4.0 version, it works well. Just dont seem to work on 0.5.0 . Python 3.8.8

**Comment by shashi792** [comment]
I had a similar issue. As suggested, switching back to 0.4.0 worked for me.

**Comment by curefatih** [comment]
`DISABLE_NEST_ASYNCIO=true` works fine for me. You should give it a try if it is suitable for your use-case.

**Comment by drazvan** [comment]
This should no longer be an issue in `0.6.0`. Please reopen if that's the case.

**Comment by analyticalpicasso** [comment]
Hello, The issue still persist in 0.7.1

**Comment by drazvan** [comment]
@analyticalpicasso : can you provide a quick log so we can check?

**Comment by analyticalpicasso** [comment]
Hello,

Below is the error log.

class RailsConfig(BaseModel):
2024-02-28 01:56:57.306 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\...\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\1215190\Documents\PortfolioOptGenAI_Guardrails\portfolio_app_test.py", line 4, in <module>
    import stock_analysis as sa
  File "C:\Users\1215190\Documents\PortfolioOptGenAI_Guardrails\stock_analysis.py", line 32, in <module>
    from nemoguardrails import RailsConfig, LLMRails
  File "C:\Users\1215190\Downloads\NeMo-Guardrails-develop\nemoguardrails\__init__.py", line 20, in <module>
    from .rails import LLMRails, RailsConfig
  File "C:\Users\1215190\Downloads\NeMo-Guardrails-develop\nemoguardrails\rails\__init__.py", line 17, in <module>
    from .llm.llmrails import LLMRails
  File "C:\Users\1215190\Downloads\NeMo-Guardrails-develop\nemoguardrails\rails\llm\llmrails.py", line 62, in <module>
    process_events_semaphore = asyncio.Semaphore(1)
  File "C:\Users\...\lib\asyncio\locks.py", line 375, in __init__
    self._loop = events.get_event_loop()
  File "C:\Users\...\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'.
2024-02-28 01:57:32.630 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\...\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\1215190\Documents\PortfolioOptGenAI_Guardrails\portfolio_app_test.py", line 4, in <module>
    import stock_analysis as sa
  File "C:\Users\1215190\Documents\PortfolioOptGenAI_Guardrails\stock_analysis.py", line 32, in <module>
    from nemoguardrails import RailsConfig, LLMRails
  File "C:\Users\1215190\Downloads\NeMo-Guardrails-develop\nemoguardrails\__init__.py", line 20, in <module>
    from .rails import LLMRails, RailsConfig
  File "C:\Users\1215190\Downloads\NeMo-Guardrails-develop\nemoguardrails\rails\__init__.py", line 17, in <module>
    from .llm.llmrails import LLMRails
  File "C:\Users\1215190\Downloads\NeMo-Guardrails-develop\nemoguardrails\rails\llm\llmrails.py", line 62, in <module>
    process_events_semaphore = asyncio.Semaphore(1)
  File "C:\Users\...\lib\asyncio\locks.py", line 375, in __init__
    self._loop = events.get_event_loop()
  File "C:\Users\...\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'.

**Comment by analyticalpicasso** [comment]
RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'.
Traceback:
File "C:\Users\...\\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
File "C:\Users\...\Documents\\...\app_test.py", line 4, in <module>
    import stock_analysis as sa
File "C:\Users\...\Documents\\...\analysis.py", line 32, in <module>
    from nemoguardrails import RailsConfig, LLMRails
File "C:\Users\...\...\nemoguardrails\__init__.py", line 20, in <module>
    from .rails import LLMRails, RailsConfig
File "C:\Users\...\...\nemoguardrails\rails\__init__.py", line 17, in <module>
    from .llm.llmrails import LLMRails
File "C:\Users\...\...\nemoguardrails\rails\llm\llmrails.py", line 62, in <module>
    process_events_semaphore = asyncio.Semaphore(1)
File "C:\Users\...\\lib\asyncio\locks.py", line 375, in __init__
    self._loop = events.get_event_loop()
File "C:\Users\...\\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'

**Comment by drazvan** [comment]
What python version?

**Comment by analyticalpicasso** [comment]
3.9.7

**Comment by analyticalpicasso** [comment]
> As a workaround, you might be able to fix this by adding:
> 
> ```python
> loop = asyncio.new_event_loop()
> asyncio.set_event_loop(loop)
> ```
> 
> in your `app_test.py` or `analysis.py` before the guardrails imports. But I would like to understand when exactly this is happening.

During import
from nemoguardrails import LLMRails, RailsConfig

**Comment by analyticalpicasso** [comment]
Currently the error is not appearing. May be got fixed by reinstalling to latest version and updating all dependencies.

**Comment by drazvan** [comment]
@botstar-tra : Can you try the develop branch? This was fixed as part of https://github.com/NVIDIA/NeMo-Guardrails/pull/627/files. Will be released in 0.10.0 in a couple of weeks.
