### ISSUE TITLE
NeMo Guardrails on LangChain with HF TGI throwing error on temperature parameter.

### ISSUE THREAD

**Issue by knowitall12** [NVIDIA/NeMo-Guardrails#206]
We are trying to use NeMo guardrils with LangChain and text generation inference as the LLM. We are getting following error: "text_generation.errors.ValidationError: `temperature` must be strictly positive" Though I am passing the temperature value in taml config file still it doesn't seems to work.
```
COLANG_CONFIG = """
define user express greeting
  "hi"

define user express insult
  "You are stupid"

# Basic guardrail against insults.
define flow
  user express insult
  bot express calmly willingness to help

# Here we use the QA chain for anything else.
define flow
  user ...
  $answer = execute qa_chain(query=$last_user_message, temperature=0.01)
  bot $answer

"""
YAML_CONFIG = """
models:
  - type: main
    engine: huggingface_textgen_inference
    model: platypus_7b
    parameters:
      inference_server_url: http://url.com
      max_new_tokens: 100
      temperature: 0.01
"""
from langchain.llms import HuggingFaceTextGenInference
from langchain.prompts import PromptTemplate

def get_chain(llm):
    prompt = PromptTemplate.from_template("tell me a joke about {foo}")
    chain = prompt | llm
    return chain

config = RailsConfig.from_content(COLANG_CONFIG, YAML_CONFIG)
app = LLMRails(config)

# Create and register the chain directly as an action.
qa_chain = get_chain(app.llm)
app.register_action(qa_chain, name="qa_chain")
app.register_action_param("temperature", 0.01)
query = "What is the current unemployment rate?"
result = qa_chain.invoke({"foo": "humans"})

print("Chain without rails:", result)

history = [
    {"role": "user", "content": "What is the current unemployment rate?"}
]
result = app.generate(messages=history)
print("Chain with rails:",result)
```

Stacktrace:
```
Error `temperature` must be strictly positive while execution generate_user_intent
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/nemoguardrails/actions/action_dispatcher.py", line 136, in execute_action
    result = await fn(**params)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/nemoguardrails/actions/llm/generation.py", line 260, in generate_user_intent
    result = await llm_call(llm, prompt)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/nemoguardrails/actions/llm/utils.py", line 31, in llm_call
    result = await llm.agenerate_prompt(
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/langchain/llms/base.py", line 461, in agenerate_prompt
    return await self.agenerate(
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/langchain/llms/base.py", line 734, in agenerate
    output = await self._agenerate_helper(
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/langchain/llms/base.py", line 636, in _agenerate_helper
    raise e
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/langchain/llms/base.py", line 623, in _agenerate_helper
    await self._agenerate(
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/langchain/llms/base.py", line 986, in _agenerate
    await self._acall(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/langchain/llms/huggingface_text_gen_inference.py", line 187, in _acall
    res = await self.async_client.generate(prompt, **invocation_params)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/text_generation/client.py", line 374, in generate
    parameters = Parameters(
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 898, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1157, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 304, in pydantic.class_validators._generic_validator_cls.lambda4
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/text_generation/types.py", line 79, in valid_temp
    raise ValidationError("`temperature` must be strictly positive")
text_generation.errors.ValidationError: `temperature` must be strictly positive
```

Output:

Chain without rails: .
What do you call a human who is scared of Santa Claus?
A Claustrophobic!
Chain with rails: {'role': 'assistant', 'content': "I'm sorry, an internal error has occurred."}

**Comment by trebedea** [comment]
As far as I can tell, the temperature problem is fixed. 

This is another error related to using chains defined using [Langchain Expression Language](https://python.langchain.com/docs/expression_language/). In Guardrails we are expecting a Langchain chain to be a subtype of class `langchain.chains.base.Chain`, see here https://github.com/NVIDIA/NeMo-Guardrails/blob/25e877831b385f8b15c3f3d4f7793f2b85a64932/nemoguardrails/actions/action_dispatcher.py#L146
For anything else, we call `result = fn.run(**params)`. 

The simplest thing to do is not to use LCEL and pass a `Chain` object as an action.

**Comment by knowitall12** [comment]
Thank you @trebedea.

**Comment by ovcharenkoo** [comment]
@trebedea Could you please post the final working version of the code? 

Thanks
