### ISSUE TITLE
OpenAI 1.2.0+ support

### ISSUE THREAD

**Issue by maxyousif15** [NVIDIA/NeMo-Guardrails#263]
I currently have an env with `openai==1.2.0` installed as the new package version is much neater for development purposes. Below is my `config.yml` file 

```
models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct
    parameters:
      temperature: 0.2

  - type: embeddings
    engine: openai
    model: text-embedding-ada-002
```

The main model works fine. However, the embedding model breaks. My FastAPI app loads fine, but any input passing through the `LLMRails` object breaks. This exception is raised during the loading of the API

```
Exception in thread Thread-1 (run):
Traceback (most recent call last):
  File ".../envs/my-env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File ".../envs/my-env/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File ".../envs/my-env/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File ".../envs/my-env/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/actions/llm/generation.py", line 106, in init
    await asyncio.gather(
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/actions/llm/generation.py", line 130, in _init_user_message_index
    await self.user_message_index.add_items(items)
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/embeddings/basic.py", line 90, in add_items
    self._embeddings.extend(self._get_embeddings([item.text for item in items]))
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/embeddings/basic.py", line 68, in _get_embeddings
    self._init_model()
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/embeddings/basic.py", line 61, in _init_model
    self._model = init_embedding_model(
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/embeddings/basic.py", line 150, in init_embedding_model
    return OpenAIEmbeddingModel(embedding_model)
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/embeddings/basic.py", line 133, in __init__
    self.embedding_size = len(self.encode(["test"])[0])
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/embeddings/basic.py", line 140, in encode
    res = openai.Embedding.create(input=documents, engine=self.model)
  File ".../envs/my-env/lib/python3.10/site-packages/openai/_utils/_proxy.py", line 22, in __getattr__
    return getattr(self.__get_proxied__(), attr)
  File ".../envs/my-env/lib/python3.10/site-packages/openai/_utils/_proxy.py", line 43, in __get_proxied__
    return self.__load__()
  File ".../envs/my-env/lib/python3.10/site-packages/openai/lib/_old_api.py", line 33, in __load__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1: 
```

The following error is returned when attempting to pass input
```
You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
 while execution generate_user_intent
Traceback (most recent call last):
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/actions/action_dispatcher.py", line 147, in execute_action
    result = await result
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/actions/llm/generation.py", line 271, in generate_user_intent
    results = await self.user_message_index.search(
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/embeddings/basic.py", line 104, in search
    _embedding = self._get_embeddings([text])[0]
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/embeddings/basic.py", line 68, in _get_embeddings
    self._init_model()
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/embeddings/basic.py", line 61, in _init_model
    self._model = init_embedding_model(
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/embeddings/basic.py", line 150, in init_embedding_model
    return OpenAIEmbeddingModel(embedding_model)
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/embeddings/basic.py", line 133, in __init__
    self.embedding_size = len(self.encode(["test"])[0])
  File ".../envs/my-env/lib/python3.10/site-packages/nemoguardrails/embeddings/basic.py", line 140, in encode
    res = openai.Embedding.create(input=documents, engine=self.model)
  File ".../envs/my-env/lib/python3.10/site-packages/openai/_utils/_proxy.py", line 22, in __getattr__
    return getattr(self.__get_proxied__(), attr)
  File ".../envs/my-env/lib/python3.10/site-packages/openai/_utils/_proxy.py", line 43, in __get_proxied__
    return self.__load__()
  File ".../envs/my-env/lib/python3.10/site-packages/openai/lib/_old_api.py", line 33, in __load__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
```

Are you planning on supporting later versions of OpenAI so that the embedding models can be used? Alternatively, are there any other solutions to overcome this problem?

**Comment by trebedea** [comment]
Hi @maxyousif15 ! 
Thanks for pointing this, looking at the OpenAI migration guide this seems like a simple change: 
https://github.com/openai/openai-python/discussions/742

`openai.Embedding.create() -> client.embeddings.create()`

Maybe you can make a MR with this change if you have the time (check for `openai` package version and use the new code for creating embeddings if `openai>=1.0.0`)

**Comment by maxyousif15** [comment]
@trebedea Sure, I can try git it my best shot! Do you have a contributing guide so that I can comply? 
Also, assuming this change is successful, when would this be released to PyPI?

**Comment by drazvan** [comment]
@maxyousif15 : we can include this for the January release. 
Related to the change, please make sure it's done in a backwards compatible way, i.e. it should work with both `openai < 1.0` and with `openai >= 1.0`. One suggestion: `if hasattr(openai, "embeddings"): ...`.

**Comment by maxyousif15** [comment]
@drazvan Something like this? 
I would swap in the below `OpenAIEmbeddingModel` object with the one defined here https://github.com/NVIDIA/NeMo-Guardrails/blob/11bf48f8a29723237528f97e5917505e7cd44f70/nemoguardrails/embeddings/basic.py#L187-L221

Is the January release at the end of the month?

```
from typing import List

from annoy import AnnoyIndex
from torch import cuda

from nemoguardrails.embeddings.index import EmbeddingModel, EmbeddingsIndex, IndexItem


class OpenAIEmbeddingModel(EmbeddingModel):
    """Embedding model using OpenAI API.

    Args:
        embedding_model (str): The name of the embedding model.

    Attributes:
        model (str): The name of the embedding model.
        embedding_size (int): The size of the embeddings.

    Methods:
        encode: Encode a list of documents into embeddings.

    """
    def __init__(self, embedding_model: str):
        self.model = embedding_model
        self.embedding_size = len(self.encode(["test"])[0])

    def encode(self, documents: List[str]) -> List[List[float]]:
        """Encode a list of documents into embeddings.

        Args:
            documents (List[str]): The list of documents to be encoded.

        Returns:
            List[List[float]]: The encoded embeddings.

        """
        import openai

        if hasattr(openai, "embeddings"):
            from openai import OpenAI
            client= OpenAI()
            res = client.embeddings.create(input=documents, model=self.model)
            embeddings = [doc.embedding for doc in res.data]
            return embeddings

        else:
            res = openai.Embedding.create(input=documents, engine=self.model)
            embeddings = [record["embedding"] for record in res["data"]]
            return embeddings
```

**Comment by drazvan** [comment]
@maxyousif15 : Yes, that looks good. And yes, the January release will be published next week (scheduled for Jan 30th).

**Comment by drazvan** [comment]
This should now be fixed.
