### ISSUE TITLE
Unable to Run fact check

### ISSUE THREAD

**Issue by analyticalpicasso** [NVIDIA/NeMo-Guardrails#357]
Hi I was running actions.py via self_fact_check but unsuccessful. As I am getting below error.

Error 'LLMTaskManager' object has no attribute 'get_stop_tokens' while execution self_check_facts
Traceback (most recent call last):
  File "path\lib\site-packages\nemoguardrails\actions\action_dispatcher.py", line 178, in execute_action
    result = await result
  File "path\Temp\ipykernel_64220\828413097.py", line 36, in self_check_facts
    stop = llm_task_manager.get_stop_tokens(task=Task.SELF_CHECK_FACTS)
AttributeError: 'LLMTaskManager' object has no attribute 'get_stop_tokens'

**Comment by drazvan** [comment]
Hi @analyticalpicasso! It seems that somehow you're mixing an older installed version with the latest code. If you've pulled the latest changes, make sure you also do `pip install -e .` again.

**Comment by drazvan** [comment]
Can you try to install from scratch version `0.8.0`, which is now published, in a fresh venv? And if it's still reproducible, do share the steps with a minimal configuration so we can look into it.
