### ISSUE TITLE
Unable to run cli chat command - nemoguardrails chat

### ISSUE THREAD

**Issue by rajatsharda23** [NVIDIA/NeMo-Guardrails#417]
I am trying to run the CLI Chat Command 'nemoguardrails chat' and getting the below error:
I made a basic python script that takes in the openai api key from as environment variable and it works just fine.
Where am I supposed to add the OPENAI_API_KEY?

Error-
Traceback (most recent call last):
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/bin/nemoguardrails", line 8, in <module>
    sys.exit(app())
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/nemoguardrails/cli/__init__.py", line 96, in chat
    run_chat(
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/nemoguardrails/cli/chat.py", line 627, in run_chat
    rails_app = LLMRails(rails_config, verbose=verbose)
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/nemoguardrails/rails/llm/llmrails.py", line 206, in __init__
    self._init_llms()
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/nemoguardrails/rails/llm/llmrails.py", line 357, in _init_llms
    self.llm = provider_cls(**kwargs)
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 120, in __init__
    super().__init__(**kwargs)
  File "/Users/rajatsharda/Desktop/ML/Nemo/.venv/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for OpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)

**Comment by drazvan** [comment]
@rajatsharda23 : what was the issue? just in case someone else runs into it as well.
