### ISSUE TITLE
UI not working - ASGI exception

### ISSUE THREAD

**Issue by javixeneize** [NVIDIA/NeMo-Guardrails#481]
Hi

I have created some basic rails and those work well with the chat. However, when i try to launch it with the UI, i have this error when i type a question 

INFO:     127.0.0.1:50912 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/homebrew/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/homebrew/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/homebrew/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/homebrew/lib/python3.9/site-packages/nemoguardrails/server/api.py", line 271, in chat_completion
    llm_rails = _get_rails(config_ids)
  File "/opt/homebrew/lib/python3.9/site-packages/nemoguardrails/server/api.py", line 228, in _get_rails
    raise Exception("Not allowed.")
Exception: Not allowed.

Is there any problem with the ASGI libraries? Im using version 0.8.3 of nemo guardrails

**Comment by Pouyanpi** [comment]
Hi @javixeneize

It seems the server has trouble reading the configs. Make sure to pass the path to the config when running the server

```bash
nemoguardrails server [--config PATH/TO/CONFIGS]
```

Note: Since the server is designed to server multiple guardrails configurations, the path/to/configs must be a folder with sub-folders for each individual config. For example:

```
.
├── config
│   ├── config_1
│   │   ├── file_1.co
│   │   └── config.yml
│   ├── config_2
│       ├── ...
│   ...
```

If you have already followed this and still facing the issue, please share with me how you are running the server, chat and the content of your configs dir, you can use (on Mac & Linux)

```
tree /path/to/config_directory
```

so that you can share it with me.

**Comment by javixeneize** [comment]
Hi

Thats the structure of my project

ls -R
config        guardrails.py

./config:
__pycache__ actions.py  config.py   config.yml  rails.co

I run it both with nemoguardrails server --config=./config

**Comment by javixeneize** [comment]
I have changed the structure now

./config:
__pycache__ javi



./config/javi:
__pycache__ actions.py  config.py   config.yml  rails.co

Still the same, running nemoguardrails server --config=./config or nemoguardrails server --config=./config/javi

In the code, i load the config as well like this

config = RailsConfig.from_path("./config")
rails = LLMRails(config)

Any idea?

Thanks

**Comment by Pouyanpi** [comment]
Hi @javixeneize !

Thanks for the info. I think you are right. As a quick fix, just try passing the absolute path to the config, instead of using relative path like "./config".

Let me know if it works then.

**Comment by javixeneize** [comment]
That works :)

Would be good if the doc is updated with that info - https://github.com/NVIDIA/NeMo-Guardrails/tree/develop/docs/getting_started/1_hello_world#server-and-chat-ui

Thanks!

**Comment by Pouyanpi** [comment]
I'm glad it resolved the issue. I agree, we need to address this properly. Thanks for opening this issue.

**Comment by drazvan** [comment]
I can give more context here. For security reasons, the paths for configs need to be normalized, and we need to make sure they are within the original server config directory. We can fix this by making sure the initial server config path is also normalized. We'll add this for `0.10.0`.

**Comment by javixeneize** [comment]
Hi
What is more important for me as an user is that this is updated in the doc. I have no problems using the abs path but the doc refers to the relative one
