### ISSUE TITLE
Installation issue on mac m1

### ISSUE THREAD

**Issue by dev-sumukha** [NVIDIA/NeMo-Guardrails#555]
I am not able to install the nemoguard rails, its giving me the following errors
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output

please look into it

**Comment by drazvan** [comment]
@dev-sumukha : can you paste the full log (starting with the `pip instal ...` command)? The above does not contain enough info.

**Comment by dev-sumukha** [comment]
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      Downloading https://snowballstem.org/dist/libstemmer_c-2.2.0.tar.gz... Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1342, in do_open
          h.request(req.get_method(), req.selector, req.data, headers,
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1255, in request
          self._send_request(method, url, body, headers, encode_chunked)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1301, in _send_request
          self.endheaders(body, encode_chunked=encode_chunked)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1250, in endheaders
          self._send_output(message_body, encode_chunked=encode_chunked)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1010, in _send_output
          self.send(msg)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 950, in send
          self.connect()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1424, in connect
          self.sock = self._context.wrap_socket(self.sock,
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
          return self.sslsocket_class._create(
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
          self.do_handshake()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
          self._sslobj.do_handshake()
      ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_w/l38_f68s02q0bf7f5vv076rh0000gn/T/pip-install-zeinye94/pystemmer_e4b603f3bcd8402fa48ea5413357cd48/setup.py", line 126, in <module>
          LIBRARY_SOURCE_CODE.download()
        File "/private/var/folders/_w/l38_f68s02q0bf7f5vv076rh0000gn/T/pip-install-zeinye94/pystemmer_e4b603f3bcd8402fa48ea5413357cd48/setup.py", line 110, in download
          download_and_extract_tarball(
        File "/private/var/folders/_w/l38_f68s02q0bf7f5vv076rh0000gn/T/pip-install-zeinye94/pystemmer_e4b603f3bcd8402fa48ea5413357cd48/tarballfetcher.py", line 40, in download_and_extract_tarball
          download_file(tarball_url, tarball_filename)
        File "/private/var/folders/_w/l38_f68s02q0bf7f5vv076rh0000gn/T/pip-install-zeinye94/pystemmer_e4b603f3bcd8402fa48ea5413357cd48/tarballfetcher.py", line 17, in download_file
          urlretrieve(url, filename)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 239, in urlretrieve
          with contextlib.closing(urlopen(url, data)) as fp:
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
          return opener.open(url, data, timeout)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
          response = self._open(req, data)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
          result = self._call_chain(self.handle_open, protocol, protocol +
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
          result = func(*args)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1385, in https_open
          return self.do_open(http.client.HTTPSConnection, req,
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1345, in do_open
          raise URLError(err)
      urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by drazvan** [comment]
This is not a guardrails-specific issue. Check out the first answer here for a potential solution: https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate.

**Comment by dev-sumukha** [comment]
thanks I will look into it
