### ISSUE TITLE
Guardrails throwing error when input message has \n

### ISSUE THREAD

**Issue by NirnayK** [NVIDIA/NeMo-Guardrails#605]
Input:
```json
{
    "config_id": "config",
    "messages": [
        {
            "role": "user",
            "content": "How to cook egg\n"
        }
    ]
}
```

Logs:
```
Event UtteranceUserActionFinished {'final_transcript': 'How to cook egg\n'}
Event StartInternalSystemAction {'uid': '2021...', 'action_name':
'create_event', 'action_params': {'event': {'_type': 'UserMessage', 'text':
'$user_message'}}, 'action_result_key': None, 'action_uid': '42a1...',
'is_system_action': True}
Executing action create_event
Event UserMessage {'uid': 'e556...', 'text': 'How to cook egg\n'}
Event StartInternalSystemAction {'uid': '0a93...', 'action_name':
'generate_user_intent', 'action_params': {}, 'action_result_key': None,
'action_uid': '849b...', 'is_system_action': True}
Executing action generate_user_intent
Phase 1 Generating user intent
Invocation Params {'model_name': 'meta-llama/Meta-Llama-3-8B-Instruct',
'temperature': 0.0, 'top_p': 1, 'frequency_penalty': 0, 'presence_penalty': 0,
'n': 1, 'logit_bias': {}, 'max_tokens': 256, '_type': 'vllm-openai', 'stop':
None}
Prompt

"""
Below is a conversation between a user and a bot called the TIR Bot.
The bot is designed to answer questions about an AI development platform called
as TIR.
The bot is knowledgeable about the features that TIR provides.
The bot does not use any external sources to answer any questions. Only use the
knowledge base for any responses. Very important.
If the bot does not know the answer to a question, it truthfully says it does
not know.
"""

# This is how a conversation between a user and the bot can go:
user "Hello there!"
  express greeting
bot express greeting
  "Hello! How can I assist you today?"
user "What can you do for me?"
  ask about capabilities
bot respond about capabilities
  "As an AI assistant, I can help you with a wide range of tasks. This includes
question answering on various topics, generating text for various purposes and
providing suggestions based on your preferences."
user "Tell me a bit about the history of NVIDIA."
  ask general question
bot response for general question
  "NVIDIA is a technology company that specializes in designing and
manufacturing graphics processing units (GPUs) and other computer hardware. The
company was founded in 1993 by Jen-Hsun Huang, Chris Malachowsky, and Curtis
Priem."
user "tell me more"
  request more information
bot provide more information
  "Initially, the company focused on developing 3D graphics processing
technology for the PC gaming market. In 1999, NVIDIA released the GeForce 256,
the world's first GPU, which was a major breakthrough for the gaming industry.
The company continued to innovate in the GPU space, releasing new products and
expanding into other markets such as professional graphics, mobile devices, and
artificial intelligence."
user "thanks"
  express appreciation
bot express appreciation and offer additional help
  "You're welcome. If you have any more questions or if there's anything else I
can help you with, please don't hesitate to ask."


# This is how the user talks:
user "hi"
  express greeting

user "hello"
  express greeting



# This is the current conversation between the user and the bot:
# Choose intent from this list: express greeting
user "Hello there!"
  express greeting
bot express greeting
  "Hello! How can I assist you today?"
user "What can you do for me?"
  ask about capabilities
bot respond about capabilities
  "As an AI assistant, I can help you with a wide range of tasks. This includes
question answering on various topics, generating text for various purposes and
providing suggestions based on your preferences."
user "How to cook egg
"

  ask about cooking
bot response for cooking
  "I'm not familiar with cooking instructions. I'm a TIR Bot, I don't have
knowledge about cooking. I can help you with questions about TIR, but not with
cooking."
user "What is TIR"
  ask about TIR
bot response about TIR
  "TIR is an AI development platform that provides a range of tools and features
for building, testing, and deploying AI models. It's designed to make AI
development more efficient and accessible, and it's used by developers and
researchers around the world."
user "What is the future of AI"
  ask about AI
bot response about AI
  "The future of AI is exciting and rapidly evolving. As AI technology continues
to advance, we can expect to see even more widespread adoption in industries
such as healthcare, finance, and education. Additionally, we can expect to see
more sophisticated AI models that are capable of learning and adapting in
complex environments."
user "What is the future of TIR"
  ask about TIR
bot response about TIR
  "The future of TIR is bright. We're constantly working to improve and expand
the platform, adding new features and tools to make AI development even more
efficient and

Output Stats {'token_usage': {'total_tokens': 800, 'prompt_tokens': 544,
'completion_tokens': 256}, 'model_name': 'meta-llama/Meta-Llama-3-8B-Instruct'}
LLM call took 3.58 seconds
Event UserIntent {'uid': '1315...', 'intent': 'ask about cooking'}
Event StartInternalSystemAction {'uid': '92a2...', 'action_name':
'generate_next_step', 'action_params': {}, 'action_result_key': None,
'action_uid': '99ed...', 'is_system_action': True}
Executing action generate_next_step
Phase 2 Generating next step ...
Invocation Params {'model_name': 'meta-llama/Meta-Llama-3-8B-Instruct',
'temperature': 0.0, 'top_p': 1, 'frequency_penalty': 0, 'presence_penalty': 0,
'n': 1, 'logit_bias': {}, 'max_tokens': 256, '_type': 'vllm-openai', 'stop':
None}
Prompt

"""
Below is a conversation between a user and a bot called the TIR Bot.
The bot is designed to answer questions about an AI development platform called
as TIR.
The bot is knowledgeable about the features that TIR provides.
The bot does not use any external sources to answer any questions. Only use the
knowledge base for any responses. Very important.
If the bot does not know the answer to a question, it truthfully says it does
not know.
"""

# This is how a conversation between a user and the bot can go:
user express greeting
bot express greeting
user ask about capabilities
bot respond about capabilities
user ask general question
bot response for general question
user request more information
bot provide more information
user express appreciation
bot express appreciation and offer additional help


# This is how the bot thinks:
user express greeting
bot express greeting



# This is the current conversation between the user and the bot:
user express greeting
bot express greeting
user ask about capabilities
bot respond about capabilities
user "How to cook egg
"
  ask about cooking

  bot "I don't know"
  user ask about capabilities
  bot respond about capabilities
  user express appreciation
  bot express appreciation and offer additional help
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities
  bot respond about capabilities
  user ask about capabilities


Output Stats {'token_usage': {'total_tokens': 476, 'prompt_tokens': 220,
'completion_tokens': 256}, 'model_name': 'meta-llama/Meta-Llama-3-8B-Instruct'}
LLM call took 3.41 seconds
Event BotIntent {'uid': '891d...', 'intent': ''}
Event StartInternalSystemAction {'uid': 'b531...', 'action_name':
'retrieve_relevant_chunks', 'action_params': {}, 'action_result_key': None,
'action_uid': 'a06a...', 'is_system_action': True}
Executing action retrieve_relevant_chunks
Searching for: How to cook egg

Searching for: How to cook egg

Searching for: How to cook egg

Found 3 results
Found 3 results
Found 3 results
Event InternalSystemActionFinished {'uid': '27f1...', 'action_uid': 'a06a...',
'action_name': 'retrieve_relevant_chunks', 'action_params': {},
'action_result_key': None, 'status': 'success', 'is_success': True,
'return_value': 'id _ here > e2e _ tir _ team _ id = < paste _ your _ team _ id
_ here > copy code you will find all the necessary data by generating a config
file from the api tokens section in the tir website. you can check out the api
token documentation to see how to generate the config file. 3. generate the
vector embeddings you can use the following code to generate vector embeddings
using our api : from e2enetworks. cloud import tir tir. init ( api _ key = tir _
api _ key, access _ token = tir _ access _ token ) tir _ client = tir.
modelapiclient ( project = tir _ project _ id, team = tir _ team _ id ) text = <
enter _ your _ text _ here > data = { " prompt " : text } model _ name = "
vector - embedding - e5 - mistral - 7b - instruct " # model name for generating
vector embeddings response = client. infer ( model _ name = model _ name, data =
data ) generated _ vector _ embeddings = response. outputs [ 0 ]. data print (
generated _ vector _ embeddings ) copy code how to insert the generated vector
embeddings into a vector database currently tir provides the following vector
databases : qdrant qdrant this guide will show you how to use our qdrant service
and insert the generated vector embeddings into a collection in the qdrant
service. how to : installing the python client using the qdrant client
connecting to the qdrant instance creating a collection adding vectors
installing the python client we are going to install the client using pip. pip
install qdrant - client copy code using the q\ngenerating vector embeddings
using tir genai api model playground is a fully - managed, low - code
environment for leveraging well - established open source and nvidia models.
customers will be able to directly access a ready - to - use api ( provided by
tir ) and don ’ t have to plan or worry about infrastructure. one of the
services provided in it is the vector embeddings service. you can call the
vector embeddings api to generate the vector embeddings of your input text. you
can use the genearted vector embeddings to use it in your model inference or
insert them in your vector database for similarity search. currently we provide
the following models for generating vector embeddings : e5 - mistral - 7b -
instruct - genearates 4096 dimentional vector embeddings for any given text.
steps to use the api : install our python client package set the environment
variables generate the vector embeddings 1. install our python client package we
provide our own python client to make it easy for you to use our apis. you can
install the client using the following command : $ pip install e2enetworks copy
code 2. set the required variables you need to set the following variables in
your python script to use the genai api : e2e _ tir _ access _ token = < paste _
your _ token _ here > e2e _ tir _ api _ key = < paste _ your _ apikey _ here >
e2e _ tir _ project _ id = < paste _ your _ project _ id _ here > e2e _ tir _
team _ id = < paste _ your _ team _ id _ here > copy code you will find all the
necessary data by generating a config file from the api tokens section in
the\n##r _ access _ token is set correctly in your notebook. # headers =
{\'authorization\':\'bearer { } \'. format ( os. environ [\'e2e _ tir _ access _
token\'] ) } copy code set endpoint url : you can get the endpoint url through
sdk ( step 4 above ) or from tir dashboard by locating the target model ’ s
endpoint. endpoint _ url = " infer. e2enetworks. net / project / < enter your
projectid > / endpoint / is - < enter inference service id > / " copy code run
the following sample code from a notebook cell import tritonclient. http as
httpclient from tritonclient. http import inferenceserverclient import gevent.
ssl as ssl import numpy as np triton _ client = inferenceserverclient ( url =
endpoint _ url, verbose = false, ssl = true, ssl _ options = { }, insecure =
false, ssl _ context _ factory = ssl. create _ default _ context ) model _ name
= " simple " # create the data for the two input tensors. initialize the first #
to unique integers and the second to all ones. input0 _ data = np. arange (
start = 0, stop = 16, dtype = np. int32 ) input0 _ data = np. expand _ dims (
input0 _ data, axis = 0 ) input1 _ data = np. full ( shape = ( 1, 16 ), fill _
value = - 1, dtype = np. int32 ) # initiate model input variable in triton
format inputs = [ ] outputs = [ ] inputs. append ( httpclient. inferinput ( "
input0', 'events': None, 'is_system_action': True}
Event StartInternalSystemAction {'uid': '5fec...', 'action_name':
'generate_bot_message', 'action_params': {}, 'action_result_key': None,
'action_uid': '5994...', 'is_system_action': True}
Executing action generate_bot_message
Phase 3 Generating bot message ...
WARNING:nemoguardrails.actions.action_dispatcher:Error while execution generate_bot_message: string index out of range
ERROR:nemoguardrails.actions.action_dispatcher:string index out of range
Traceback (most recent call last):
  File "/nemoguardrails/nemoguardrails/actions/action_dispatcher.py", line 197, in execute_action
    result = await result
  File "/nemoguardrails/nemoguardrails/actions/llm/generation.py", line 739, in generate_bot_message
    elif bot_intent[0] == "$" and bot_intent[1:] in context:
IndexError: string index out of range
Event hide_prev_turn {}
Total processing took 7.64 seconds. LLM Stats: 2 total calls, 6.99 total time,
1276 total tokens, 764 total prompt tokens, 512 total completion tokens, [3.58,
3.41] as latencies
INFO:     10.0.4.240:51472 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```

**Comment by drazvan** [comment]
Thanks for reporting this @NirnayK! There's a mix of bugs here related to the "\n", the default prompt which does not work well for Llama-3-8b, the completion generating too many lines. We're in the middle of fixing some of these, including providing a better prompt for Llama3. Mid next-week these should land in the `develop` branch.

**Comment by m4salem** [comment]
Hello, any updates on this issue, it also affects having custom llama 3 RAGs with the nemo guardrails.

**Comment by Pouyanpi** [comment]
@m4salem Are you still facing this issue? If so, which version of NeMo Guardrails are you using?
@NirnayK could you try v0.10.0 which was released recently?

**Comment by m4salem** [comment]
@Pouyanpi I am trying to run it with the huggingfacepipeline/huggingfacepipelinecompatible and Lllama 3. Mostly getting the error 
```
if param not in self.llm.model_kwargs:
TypeError: argument of type 'NoneType' is not iterable
content="I'm sorry, an internal error has occurred."
```

**Comment by m4salem** [comment]
@Pouyanpi I tried to narrow down the issue, but I believe it is the llama 3 model does not properly generate responses that let the rest of the flows (user intent, bot intent) continue normally. As a result, Nemo always generates a response that "it can not answer the question. " regardless of whether the prompt allows or blocks the question.

**Comment by ramchennuru** [comment]
Hey @Pouyanpi , I tried with the llama3 model and it is giving proper responses only even it has "\n" in the input question.
