### ISSUE TITLE
Nemo Guardrails on Lambda FileNotFoundError with '.cache/embeddings'

### ISSUE THREAD

**Issue by Karthikreddyk99** [NVIDIA/NeMo-Guardrails#608]
Exception in thread Thread-1 (run):
Traceback (most recent call last):
File "/var/lang/lib/python3.12/pathlib.py", line 1311, in mkdir
os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '.cache/embeddings'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/lang/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
self.run()
File "/var/lang/lib/python3.12/threading.py", line 1010, in run
self._target(*self._args, **self._kwargs)
File "/var/task/nest_asyncio.py", line 30, in run
return loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/task/nest_asyncio.py", line 98, in run_until_complete
return f.result()
^^^^^^^^^^
File "/var/lang/lib/python3.12/asyncio/futures.py", line 203, in result
raise self._exception.with_traceback(self._exception_tb)
File "/var/lang/lib/python3.12/asyncio/tasks.py", line 316, in __step_run_and_handle_result
result = coro.throw(exc)
^^^^^^^^^^^^^^^
File "/var/task/nemoguardrails/actions/llm/generation.py", line 125, in init
await asyncio.gather(
File "/var/lang/lib/python3.12/asyncio/tasks.py", line 385, in __wakeup
future.result()
File "/var/lang/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
result = coro.send(None)
^^^^^^^^^^^^^^^
File "/var/task/nemoguardrails/actions/llm/generation.py", line 247, in _init_bot_message_index
await self.bot_message_index.add_items(items)
File "/var/task/nemoguardrails/embeddings/basic.py", line 177, in add_items
await self._get_embeddings([item.text for item in items])
File "/var/task/nemoguardrails/embeddings/cache.py", line 305, in wrapper_decorator
embeddings_cache = EmbeddingsCache.from_config(self.cache_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/task/nemoguardrails/embeddings/cache.py", line 220, in from_config
return cls.from_dict(config.to_dict())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/task/nemoguardrails/embeddings/cache.py", line 213, in from_dict
cache_store = CacheStore.from_name(d.get("store"))(**store_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/task/nemoguardrails/embeddings/cache.py", line 143, in __init__
self._cache_dir.mkdir(parents=True, exist_ok=True)
File "/var/lang/lib/python3.12/pathlib.py", line 1315, in mkdir
self.parent.mkdir(parents=True, exist_ok=True)
File "/var/lang/lib/python3.12/pathlib.py", line 1311, in mkdir
os.mkdir(self, mode)
OSError: [Errno 30] Read-only file system: '.cache'

I tried to directly make changes in the library from my code,
```
import next_asyncio
from nemoguardrails import RailsConfig
from nemoguardrails.integrations.langchain.runnable_rails import RunnableRails
from nemoguardrails.embeddings.cache import EmbeddingsCache, EmbeddingsCacheConfig

# Use the /tmp directory provided by Lambda
tmp_dir = Path('/tmp')
cache_dir = tmp_dir / 'embeddings'
cache_dir.mkdir(parents=True, exist_ok=True)
os.environ['NEMOGUARDRAILS_CACHE_DIR'] = str(cache_dir)

# Create an EmbeddingsCacheConfig
cache_config = EmbeddingsCacheConfig(
    enabled=True,
    key_generator="md5",  # Use a recognized key generator
    store="filesystem",  # Use the "filesystem" option for file-based caching
    store_config={
        "cache_dir": str(cache_dir)
    }
)

# Create an instance of EmbeddingsCache using the from_config method
cache = EmbeddingsCache.from_config(cache_config)

nest_asyncio.apply()

```
**But still I have issue persisting**

**Comment by Karthikreddyk99** [comment]
https://github.com/NVIDIA/NeMo-Guardrails/issues/508#issuecomment-2128897688

i created the empty directory .cache/embeddings and resolved this using the above comment.
