### ISSUE TITLE
Error excuting Hello World: Failed to deserialize the JSON body into the target type: prompt: invalid type: sequence, expected a string

### ISSUE THREAD

**Issue by XDcsy** [NVIDIA/NeMo-Guardrails#680]
The hello world script:

``` python
from nemoguardrails import RailsConfig
from nemoguardrails import LLMRails

config = RailsConfig.from_path("./config")
rails = LLMRails(config)

response = rails.generate(messages=[{
    "role": "user",
    "content": 'Hello!'
}])
print(response["content"])
```

The error is:

```
(nemonew) @XDcsy ➜ /workspaces/codespaces-blank $ python testnemo.py 
Fetching 5 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 67869.00it/s]
Traceback (most recent call last):
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/nemoguardrails/actions/llm/utils.py", line 69, in llm_call
    result = await llm.agenerate_prompt(
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 760, in agenerate_prompt
    return await self.agenerate(
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1183, in agenerate
    output = await self._agenerate_helper(
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1023, in _agenerate_helper
    raise e
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1007, in _agenerate_helper
    await self._agenerate(
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/langchain_openai/llms/base.py", line 428, in _agenerate
    response = await self.async_client.create(prompt=_prompts, **params)
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/openai/resources/completions.py", line 1059, in create
    return await self._post(
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/openai/_base_client.py", line 1816, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/openai/_base_client.py", line 1510, in request
    return await self._request(
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/openai/_base_client.py", line 1611, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: prompt: invalid type: sequence, expected a string at line 1 column 37

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/codespaces-blank/testnemo.py", line 7, in <module>
    response = rails.generate(messages=[{
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/nemoguardrails/rails/llm/llmrails.py", line 886, in generate
    return loop.run_until_complete(
  File "/usr/local/python/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/nemoguardrails/rails/llm/llmrails.py", line 647, in generate_async
    new_events = await self.runtime.generate_events(
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/nemoguardrails/colang/v1_0/runtime/runtime.py", line 167, in generate_events
    next_events = await self._process_start_action(events)
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/nemoguardrails/colang/v1_0/runtime/runtime.py", line 363, in _process_start_action
    result, status = await self.action_dispatcher.execute_action(
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/nemoguardrails/actions/action_dispatcher.py", line 236, in execute_action
    raise e
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/nemoguardrails/actions/action_dispatcher.py", line 197, in execute_action
    result = await result
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/nemoguardrails/actions/llm/generation.py", line 405, in generate_user_intent
    result = await llm_call(llm, prompt)
  File "/workspaces/codespaces-blank/nemonew/lib/python3.10/site-packages/nemoguardrails/actions/llm/utils.py", line 73, in llm_call
    raise LLMCallException(e)
nemoguardrails.actions.llm.utils.LLMCallException: LLM Call Exception: Failed to deserialize the JSON body into the target type: prompt: invalid type: sequence, expected a string at line 1 column 37
```

I found a temporary solution for this by editing `.../lib/python3.10/site-packages/openai/resources/completions.py, line 1064`, changing `"prompt": prompt` to **`"prompt": " ".join(prompt)`**

```
            body=await async_maybe_transform(
                {
                    "model": model,
                    "prompt": " ".join(prompt),                   # <--- here
                    "best_of": best_of,
                    "echo": echo,
                    "frequency_penalty": frequency_penalty,
                    "logit_bias": logit_bias,
                    "logprobs": logprobs,
                    "max_tokens": max_tokens,
                    "n": n,
                    "presence_penalty": presence_penalty,
                    "seed": seed,
                    "stop": stop,
                    "stream": stream,
                    "stream_options": stream_options,
                    "suffix": suffix,
                    "temperature": temperature,
                    "top_p": top_p,
                    "user": user,
                },
```

The nemoguardrails and Openai packages are installed by `pip install nemoguardrails[openai]`. Here are the versions:
```
Name: nemoguardrails
Version: 0.9.1.1
Name: openai
Version: 1.41.0
```

I am using an OpenAI API compatible LLM service, which seems to me the most suspicious cause. But the error occurred before the API call was made (and the model works after my temporary fix). So I'm still not sure about the exact cause of it.

The `config.yml` file I'm using:

```
models:
 - type: main
   engine: openai
   model: deepseek-chat
   parameters: 
     openai_api_base: "https://api.deepseek.com/beta"
     model_name: "deepseek-chat"
```

**Comment by Pouyanpi** [comment]
Hi @XDcsy,

The issue you're encountering stems from the fact that `deepseek-chat` is not provided by OpenAI, so it can't be used with the "openai" engine directly.



### Solution: Implement a Custom LLM Provider

To properly integrate `deepseek-chat`, you need to implement a [custom LLM provider](https://github.com/NVIDIA/NeMo-Guardrails/blob/1eedf07c72ec7a332b2ae7d9cbd98ac55688c0cf/docs/user_guides/configuration-guide.md?plain=1#L234) (see  [this](https://python.langchain.com/v0.1/docs/modules/model_io/llms/custom_llm/) for more info) and register it within `NeMo Guardrails`. 



### Verification: Using the OpenAI Engine
If you set the LLM engine to OpenAI, `NeMo Guardrails` will utilize the OpenAI model via `langchain_openai`. However, this won’t work for `deepseek-chat` because it’s not an OpenAI model. For example, if you try the following code:

```python
from langchain_openai import OpenAI

model = OpenAI(model="deepseek-chat", base_url="https://api.deepseek.com/beta")
model.invoke("hi")
```
You'll encounter the same error. 

Another option is using `vllm_openai` engine
```py
models:
  - type: main
    engine: vllm_openai
    model_name: deepseek-chat
    parameters:
      openai_api_base: "https://api.deepseek.com/beta"
      model_name: "deepseek-chat"
```
but you'll face the same issue as DeepSeek seem to be not compatible to communicate with langchain.


Also it is worth to consider the prompts used under the hood, `NeMo Guardrails` uses a heuristic to select prompts based on the model and engine. With your configuration, it’s likely defaulting to an "[unknown.yml](https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/llm/prompts/unknown.yml)" prompt.


Please let me know how you progress. I'd suggest you to also mention it to DeepSeek. They might be able to fix the API such that it could be used with `OpenAI` from langchain .

**Comment by XDcsy** [comment]
It's true. The error is caused due to the API's compatibility :)
