### ISSUE TITLE
Exception: Unknown LLM engine: SentenceTransformers.

### ISSUE THREAD

**Issue by pradeepdev-1995** [NVIDIA/NeMo-Guardrails#685]
Tried to load the embedding model from path
```
colang_content=""" """
yaml_content = """
instructions:
  - type: general
    content: |
      You are an AI assistant that supports ABC company queries
rails:
  dialog:
    user_messages:
      embeddings_only: True
models:
   - type: embedding
     engine: SentenceTransformers
     model: all-MiniLM-L6-v2
"""
from nemoguardrails import LLMRails, RailsConfig
config = RailsConfig.from_content(
    yaml_content=yaml_content,
    colang_content=colang_content
)

rails = LLMRails(config)
```
But getting this error
```
Exception: Unknown LLM engine: SentenceTransformers.

```
detailed logs
```
>> from langchain.llms import HuggingFacePipeline

with new imports of:

>> from langchain_community.llms import HuggingFacePipeline
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  warn_deprecated(
/home/local/lib/python3.9/site-packages/langchain/_api/module_import.py:92: LangChainDeprecationWarning: Importing ZapierNLAWrapper from langchain.utilities is deprecated. Please replace deprecated imports:

>> from langchain.utilities import ZapierNLAWrapper

with new imports of:

>> from langchain_community.utilities import ZapierNLAWrapper
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  warn_deprecated(
Traceback (most recent call last):
  File "/home/nemo_offtopic.py", line 227, in <module>
    rails = LLMRails(config)
  File "/home/llmrails.py", line 204, in __init__
    self._init_llms()
  File "/home/llmrails.py", line 321, in _init_llms
    raise Exception(msg)
Exception: Unknown LLM engine: SentenceTransformers.
```

**Comment by Pouyanpi** [comment]
Hi @pradeepdev-1995, the type must be `embeddings` instead of `embedding`.

**Comment by Pouyanpi** [comment]
@pradeepdev-1995, did it resolve your issue?

**Comment by pradeepdev-1995** [comment]
@Pouyanpi  yes ```embeddings``` solved my issue
