### ISSUE TITLE
Older LangChain Dependency ( 0.0.137 ) breaks asynchronous Execution

### ISSUE THREAD

**Issue by unownone** [NVIDIA/NeMo-Guardrails#9]
I am using langchain (`^0.0.141`) and it works perfectly for our see needs by creating a `asyncio.create_task` and a asyncio.Queue() to listen from. 

But `NeMo-Guardrails==0.1.0` requires `langchain==0.0.137` which throws an unimplemented error every time the coroutine is called.

```python
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Chain.acall() done, defined at path/to/.venv/lib/python3.10/site-packages/langchain/chains/base.py:120> exception=NotImplementedError()>
Traceback (most recent call last):
  File "path/to/.venv/lib/python3.10/site-packages/langchain/chains/base.py", line 154, in acall
    raise e
  File "path/to/.venv/lib/python3.10/site-packages/langchain/chains/base.py", line 148, in acall
    outputs = await self._acall(inputs)
  File "path/to/.venv/lib/python3.10/site-packages/langchain/chains/conversational_retrieval/base.py", line 103, in _acall
    docs = await self._aget_docs(new_question, inputs)
  File "path/to/.venv/lib/python3.10/site-packages/langchain/chains/conversational_retrieval/base.py", line 150, in _aget_docs
    docs = await self.retriever.aget_relevant_documents(question)
  File "path/to/.venv/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 236, in aget_relevant_documents
    docs = await self.vectorstore.asimilarity_search(
  File "path/to/.venv/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 84, in asimilarity_search
    raise NotImplementedError
NotImplementedError
```

**Comment by drazvan** [comment]
Fixed by https://github.com/NVIDIA/NeMo-Guardrails/commit/327da8a42d5f815d97e4123b7f23666674baf92f. Thanks for reporting!
