### ISSUE TITLE
Argument of type `property` is not iterable

### ISSUE THREAD

**Issue by JonoCX** [NVIDIA/NeMo-Guardrails#92]
Hi there -

I'm running into an issue where the `model_kwargs` for a HuggingFace pipeline are not recognised and not parsed. 

From what I can tell, the `model_kwargs` exist but it's producing an object that isn't iterable, which looks to be a bug unless I'm misunderstanding how NeMo is parsing the parameters(?)

Here's the code:

```python
from langchain.llms import HuggingFacePipeline
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
from nemoguardrails import RailsConfig, LLMRails
from nemoguardrails.llm.helpers import get_llm_instance_wrapper

MODEL_ID = 'gpt2'
MODEL_ARGS = {
    'max_new_tokens': 10,
    'max_length': 30,
    'temperature': 0.0
}
CONFIG_FILE = 'config.co'

GREETING = 'Hello there!'

tokenizer =AutoTokenizer.from_pretrained(pretrained_model_name_or_path=MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    pretrained_model_name_or_path=MODEL_ID
)
pipe = pipeline(
    task='text-generation',
    model=model,
    tokenizer=tokenizer,
    model_kwargs=MODEL_ARGS
)

llm = get_llm_instance_wrapper(
    llm_instance=HuggingFacePipeline(pipeline=pipe), 
    llm_type='HuggingFacePipeline'
)
config = RailsConfig.from_content(colang_content=CONFIG_FILE)
app = LLMRails(config, llm=llm, verbose=True)

has = hasattr(hg_pipe, 'model_kwargs')} # has = True
fetch = getattr(hg_pipe, 'model_kwargs', {}) # fetch = <property object at 0x13d4eb0b0>

new_message = app.generate(messages=[{
    'role': 'user',
    'content': GREETING
}])
```

Here's the stack trace, which is thrown at the point of `app.generate()`:

```bash
Error argument of type 'property' is not iterable while execution generate_user_intent
Traceback (most recent call last):
  File ".../venv/lib/python3.10/site-packages/nemoguardrails/actions/action_dispatcher.py", line 125, in execute_action
    result = await fn(**params)
  File ".../venv/lib/python3.10/site-packages/nemoguardrails/actions/llm/generation.py", line 269, in generate_user_intent
    with llm_params(llm, temperature=self.config.lowest_temperature):
  File ".../venv/lib/python3.10/site-packages/nemoguardrails/llm/params.py", line 44, in __enter__
    elif hasattr(self.llm, "model_kwargs") and param in getattr(
TypeError: argument of type 'property' is not iterable
```

Here's the versions of the libraries used (with python==3.10.12):

```
langchain==0.0.251
transformers==4.31.0
nemoguardrails==0.4.0
```

Any help or guidance here would be great, especially if I'm missing something obvious!

**Comment by serhatgktp** [comment]
Do you have the full stack trace, starting from this script that you are trying to run?

**Comment by JonoCX** [comment]
Hey, thanks for the response!

Here's the full stack trace:

```
2023-08-10 08:05:59.240348: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
.../venv/lib/python3.10/site-packages/transformers/generation/utils.py:1369: UserWarning: Using `max_length`'s default (50) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
.../simple_experiment/config.py:43: FutureWarning: The 'transformers' MLflow Models integration is known to be compatible with the following package version ranges: ``4.25.1`` -  ``4.30.2``. MLflow Models integrations with transformers may not succeed when used with package versions outside of this range.
  pipeline_info = mlflow.transformers.log_model(
.../venv/lib/python3.10/site-packages/mlflow/models/model.py:572: FutureWarning: The 'transformers' MLflow Models integration is known to be compatible with the following package version ranges: ``4.25.1`` -  ``4.30.2``. MLflow Models integrations with transformers may not succeed when used with package versions outside of this range.
  flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
2023/08/10 08:06:11 WARNING mlflow.transformers: Could not infer model execution engine type due to huggingface_hub not being installed or unable to connect in online mode. Adding full dependency chain: ['transformers==4.31.0', 'torch==2.0.1', 'torchvision==0.15.2', 'tensorflow==2.13.0']. 
Failure cause: No module named 'accelerate'
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
.../venv/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2023/08/10 08:06:19 WARNING mlflow.transformers: Could not specify device parameter for this pipeline type
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
.../venv/lib/python3.10/site-packages/transformers/generation/utils.py:1369: UserWarning: Using `max_length`'s default (50) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
.../venv/lib/python3.10/site-packages/transformers/generation/utils.py:1369: UserWarning: Using `max_length`'s default (50) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
Error argument of type 'property' is not iterable while execution generate_user_intent
Traceback (most recent call last):
  File ".../venv/lib/python3.10/site-packages/nemoguardrails/actions/action_dispatcher.py", line 125, in execute_action
    result = await fn(**params)
  File ".../venv/lib/python3.10/site-packages/nemoguardrails/actions/llm/generation.py", line 269, in generate_user_intent
    with llm_params(llm, temperature=self.config.lowest_temperature):
  File ".../venv/lib/python3.10/site-packages/nemoguardrails/llm/params.py", line 44, in __enter__
    elif hasattr(self.llm, "model_kwargs") and param in getattr(
TypeError: argument of type 'property' is not iterable
```

**Comment by shabie** [comment]
I ran your code and for me 

`hasattr(pipe, 'model_kwargs')} `

is False (and hence I do get the error)

**Comment by shabie** [comment]
So I think I found two places where the problem is.

So here the class instance is not being initialized i.e. it should be `return WrapperLLM()`:

https://github.com/NVIDIA/NeMo-Guardrails/blob/12c49bb99ee327f21fa8a7e31f97cef505b6fff1/nemoguardrails/llm/helpers.py#L67

Furthermore, this part:

```python
llm = get_llm_instance_wrapper(
    llm_instance=HuggingFacePipeline(pipeline=pipe), 
    llm_type='HuggingFacePipeline'
)
```

needs to have the `model_kwargs` separately again:

```python
llm = get_llm_instance_wrapper(
    llm_instance=HuggingFacePipeline(pipeline=pipe, , model_kwargs=MODEL_ARGS), 
    llm_type='HuggingFacePipeline'
)
```

I can create a PR for initialization but I am not sure how to fix this less than elegant double passing of MODEL_ARGS once to pipeline and then again to the langchain component.

**Comment by serhatgktp** [comment]
@shabie if you instantiate the `WrapperLLM` instance when returning, the `@property` tag in lines [32-41](https://github.com/NVIDIA/NeMo-Guardrails/blob/12c49bb99ee327f21fa8a7e31f97cef505b6fff1/nemoguardrails/llm/helpers.py#L32-L41) from `nemoguardrails/llm/helpers.py` already propagates the `model_kwargs` from the initial LLM as an attribute in the returned `WrapperLLM` instance, so you wouldn't have to worry about that.

**Comment by shabie** [comment]
So you mean that the `model_kwargs` dict is bound to the class definition and hence doesn't need to be initialized.

**Comment by serhatgktp** [comment]
Correct, it is already added as an attribute to the `WrapperLLM` instance in `get_llm_instance_wrapper`.

**Comment by trebedea** [comment]
Hi everyone,

Thanks for the discussion here, I'm glad you've found a work-around for this. 

However, the intended usage for the `WrapperLLM` functionality is similar to the Guardrails examples presented for [HuggingFace pipeline](https://github.com/NVIDIA/NeMo-Guardrails/blob/12c49bb99ee327f21fa8a7e31f97cef505b6fff1/examples/llm/hf_pipeline_dolly/config.py#L39C9-L43C13). That means that for each each LLM engine we want to register a Langchain `langchain.llms.base.LLM` class able to interact with that specific LLM. This class is then instantiated by any `LLMRails` instance at initialization.

So we want to do something like this:

```
HFPipelineGPT2 = get_llm_instance_wrapper(
        llm_instance=HuggingFacePipeline(pipeline=pipe, model_kwargs=MODEL_ARGS),
        llm_type='hf_pipepline_gpt2'
    )
# register the class to process the new LLM engine/type called "hf_pipepline_gpt2"
register_llm_provider("hf_pipepline_gpt2", HFPipelineGPT2)
```

Now you can use this LLM for any Guardrails app by specifying the name in the `config.yml`, e.g.:

```
models:
  - type: main
    engine: hf_pipepline_gpt2
```

Putting things back into the code provided by @JonoCX , we have the following solution:

```
tokenizer =AutoTokenizer.from_pretrained(pretrained_model_name_or_path=MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    pretrained_model_name_or_path=MODEL_ID
)
pipe = pipeline(
    task='text-generation',
    model=model,
    tokenizer=tokenizer,
#  model_kwargs=MODEL_ARGS,    # for some reason, this does not propagate the parameters to the model, the next line works
    kwargs=**MODEL_ARGS,
)

# create the class / type for the 'hf_pipepline_gpt2' LLM engine
# and yes, we need to specify model_kwargs here again
HFPipelineGPT2 = get_llm_instance_wrapper(
    llm_instance=HuggingFacePipeline(pipeline=pipe, model_kwargs=MODEL_ARGS),
    llm_type='hf_pipepline_gpt2'
)
# register it as a LLM provider for Guardrails
register_llm_provider("hf_pipepline_gpt2", HFPipelineGPT2)

# here, use loading an app from a path, where you have both .co and .yml files
# you can also use loading from a string, but you need to specify also the content of the 'config.yml' file
# config = RailsConfig.from_content(colang_content=CONFIG_FILE)
path_to_app = "ADD PATH HERE"
config = RailsConfig.from_path(config_path=path_to app)
# don't send the LLM instance here, the LLMRails initialization will create the required object as needed
app = LLMRails(config, verbose=True)

new_message = app.generate(messages=[{
    'role': 'user',
    'content': GREETING
}])

# this should work now.
print(new_message)
```

@shabie , no need for a PR as this is the intended usage. 
Hope this helps and makes sense.

**Comment by trebedea** [comment]
@JonoCX , if this solves your problem, I think we can close this issue.

**Comment by JonoCX** [comment]
@trebedea Epic, thank you! I can confirm that the above works, thanks for the help 🙏🏻
